### PR TITLE
Feature/allow anonymous bind

### PR DESCRIPTION
**Pull request by markusstoll**

### CODE REVIEW

**Comment by localleon** [comment]
Hey, thanks for you contribution.

I will take a look in the next days and test it out

**Comment by maxguru** [comment]
@markusstoll, thank you.

Can you please fix the indentation in [e730579](https://github.com/gitea-group-sync/gitea-group-sync/pull/13/commits/e730579b14b23fbb5bf328c8c79c0cc38adb5731)?

**Comment by markusstoll** [comment]
I am a newbe to GO, so sorry
done

**Comment by maxguru** [comment]
Thanks!

**Review by localleon — APPROVED** [review]
Looks good to me! Works with my local testing enviroment 

We can ignore the failing "lint" test. This is another problem

**Comment by maxguru** [comment]
@localleon thanks a lot!

By the way, I saw there was an issue with the [lint job](https://github.com/gitea-group-sync/gitea-group-sync/runs/2818020056).

**Comment by localleon** [comment]
@maxguru Hey, i saw that one too. Fixed the "lint"-Action, it was justing missing a correct `go.sum` file

**Pull request merged**
